[package]
name = "wreq-python"
version = "0.12.3"
description = "An ergonomic, privacy-aware Python HTTP Client"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/0x676e67/wreq-python"
authors = ["0x676e67 <gngppz@gmail.com>"]
edition = "2024"
rust-version = "1.98"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "wreq"
crate-type = ["cdylib"]
doctest = false

[features]
default = ["abi3-py311"]

# Memory allocator options
jemalloc = ["dep:tikv-jemallocator"]
mimalloc = ["dep:mimalloc"]

# we build cp311-abi3 and cp310 wheels now, move this to pyo3 after we drop cp310
abi3-py311 = ["pyo3/abi3-py311"]
abi3-py313 = ["pyo3/abi3-py313"]
abi3-py314 = ["pyo3/abi3-py314"]

[dependencies]
pingora-runtime = "0.9.0"
tokio = { version = "1.52.2", features = ["rt-multi-thread", "sync", "time", "net"] }
tokio-util = { version = "0.7.18", features = ["rt"] }
pyo3 = { version = "0.29.0", features = [
    "indexmap",
    "multiple-pymethods",
    "extension-module",
    "generate-import-lib",
] }
futures-util = { version = "0.3.33", default-features = false, features = ["std"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7.1"
indexmap = { version = "2.13.0", features = ["serde"] }
bytes = "1.12.1"
arc-swap = "1.9.2"
http = "1.4.2"
http-body-util = "0.1.4"
wreq = { version = "0.16.1", default-features = false, features = [
    "webpki-roots",
    "tokio-rt",
    "query",
    "form",
    "json",
    "socks",
    "stream",
    "multipart",
    "cookies",
    "charset",
    "gzip",
    "brotli",
    "deflate",
    "zstd",
    "ws",
    "parking_lot",
] }
wreq-util = { version = "0.2.0", features = ["emulation-compression"] }
hickory-resolver = "0.26.3"
cookie = "0.18.2"
mimalloc = { version = "0.1.43", default-features = false, features = [
    "local_dynamic_tls",
], optional = true }
tikv-jemallocator = { version = "0.7.0", default-features = false, features = [
    "disable_initial_exec_tls",
], optional = true }

# Keep the latest emulation profiles and their required TLS support in sync.
[patch.crates-io]
wreq-util = { git = "https://github.com/0x676e67/wreq-util", rev = "5715529002738f46eea86a7271f918f9374d3582" }
# demo/netty-migration
wreq = { git = "https://github.com/0x676e67/wreq", rev = "54fdc7c9e0c1290e2f70f38d271ba954e3d86cc2" }
# demo/tokio-btls-vectored-write
btls = { git = "https://github.com/0x676e67/btls", rev = "ffaf0e8c23d455af4e306986ce81bb57ebd03bc2" }
btls-sys = { git = "https://github.com/0x676e67/btls", rev = "ffaf0e8c23d455af4e306986ce81bb57ebd03bc2" }
tokio-btls = { git = "https://github.com/0x676e67/btls", rev = "ffaf0e8c23d455af4e306986ce81bb57ebd03bc2" }
# main (0x676e67/netty#145)
netty = { git = "https://github.com/0x676e67/netty", rev = "f8652ddf5e386d66b7f03cceedbc6b319d849762" }

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = true
